global:
  scrape_interval: 30s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - 'alert-manager:9093'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets:
        - 'localhost:9090'
  
  - job_name: 'pushgateway'
    static_configs:
      - targets:
        - 'pushgateway:9091'